swagger:
  title: Manager Server
  description: Manager Server API Document
  version: 1.0.0
  contact:
    name: wangming
    url: http://geomodeling.njnu.edu.cn/
    email: wangminggis@163.com
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  resources:
    static-locations: ["classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/", "file:${prop.task-uploadr}"]
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/Manager
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: D:/portal/temp
  mvc:
    static-path-pattern: /**

server:
  port: 8090
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/css
      - text/xml
      - text/plain
      - application/javascript
    min-response-size: 1024
  servlet:
    session:
      timeout: 60
